# Generated by Django 5.2.13 on 2026-09-19 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_pari_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('final_label', models.CharField(choices=[('Benign', 'Benign'), ('Phishing', 'Phishing'), ('Malware', 'Malware'), ('Defacement', 'Defacement'), ('Still Unknown', 'Still Unknown')], max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=[('VALIDATED', 'Validated for future training'), ('NOT_VALIDATED', 'Not validated')], default='NOT_VALIDATED', max_length=20)),
            ],
            options={
                'db_table': 'pari_analyst_review',
            },
        ),
        migrations.RenameIndex(
            model_name='domain',
            new_name='pari_domain_domain__567b72_idx',
            old_name='pari_domain_domain_n_idx',
        ),
        migrations.RenameIndex(
            model_name='domain',
            new_name='pari_domain_status_6444c0_idx',
            old_name='pari_domain_status_idx',
        ),
        migrations.RenameIndex(
            model_name='domain',
            new_name='pari_domain_risk_sc_e824c8_idx',
            old_name='pari_domain_risk_sco_idx',
        ),
        migrations.RenameIndex(
            model_name='ip',
            new_name='pari_ip_ip_addr_50126a_idx',
            old_name='pari_ip_ip_addres_idx',
        ),
        migrations.RenameIndex(
            model_name='ip',
            new_name='pari_ip_status_56e9d2_idx',
            old_name='pari_ip_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ip',
            new_name='pari_ip_risk_sc_a94b2d_idx',
            old_name='pari_ip_risk_score_idx',
        ),
        migrations.RenameIndex(
            model_name='prediction',
            new_name='pari_predic_predict_619ced_idx',
            old_name='pari_predict_predicte_idx',
        ),
        migrations.RenameIndex(
            model_name='prediction',
            new_name='pari_predic_confide_33cf41_idx',
            old_name='pari_predict_confide_idx',
        ),
        migrations.RenameIndex(
            model_name='prediction',
            new_name='pari_predic_risk_sc_80d0d4_idx',
            old_name='pari_predict_risk_sco_idx',
        ),
        migrations.RenameIndex(
            model_name='scan',
            new_name='pari_scan_status_965a60_idx',
            old_name='pari_scan_status_idx',
        ),
        migrations.RenameIndex(
            model_name='scan',
            new_name='pari_scan_user_id_f588c4_idx',
            old_name='pari_scan_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='scan',
            new_name='pari_scan_created_e39e1f_idx',
            old_name='pari_scan_created__idx',
        ),
        migrations.RenameIndex(
            model_name='scanindicator',
            new_name='pari_scan_i_scan_id_6c67f8_idx',
            old_name='pari_scan__scan_id_idx',
        ),
        migrations.RenameIndex(
            model_name='scanindicator',
            new_name='pari_scan_i_indicat_c73b73_idx',
            old_name='pari_scan__indicat_idx',
        ),
        migrations.RenameIndex(
            model_name='threatindicator',
            new_name='pari_threat_indicat_c78d26_idx',
            old_name='pari_threat__indicat_idx',
        ),
        migrations.RenameIndex(
            model_name='threatindicator',
            new_name='pari_threat_severit_00cfce_idx',
            old_name='pari_threat__severity_idx',
        ),
        migrations.RenameIndex(
            model_name='url',
            new_name='pari_url_url_21efb6_idx',
            old_name='pari_url_url_idx',
        ),
        migrations.RenameIndex(
            model_name='url',
            new_name='pari_url_source_a6e48a_idx',
            old_name='pari_url_source_idx',
        ),
        migrations.RenameIndex(
            model_name='url',
            new_name='pari_url_domain__7357d0_idx',
            old_name='pari_url_domain_idx',
        ),
        migrations.AlterField(
            model_name='domain',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maliciousbot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scanindicator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='threatindicator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='analystreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),

        migrations.AddField(
            model_name='analystreview',
            name='scan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_review', to='User.scan'),
        ),
    ]
