# Generated by Django 5.2.13 on 2026-09-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_historyclearevent_userdatabaseregistry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_len', models.IntegerField(help_text='Total character length of the URL string.')),
                ('letters_count', models.IntegerField(help_text='Count of ASCII letter characters in the URL.')),
                ('digits_count', models.IntegerField(help_text='Count of digit characters in the URL.')),
                ('special_chars_count', models.IntegerField(help_text='Count of non-alphanumeric/non-period characters in the URL.')),
                ('shortened', models.SmallIntegerField(help_text='1 if URL uses a known shortening service, else 0.')),
                ('abnormal_url', models.SmallIntegerField(help_text='1 if URL exhibits abnormal structure (existing PARI logic), else 0.')),
                ('secure_http', models.SmallIntegerField(help_text='1 if URL scheme is HTTPS, else 0.')),
                ('have_ip', models.SmallIntegerField(help_text='1 if URL host is an IP address rather than a domain name, else 0.')),
                ('url_region', models.BigIntegerField(help_text='Hash-encoded country/region of the primary domain TLD.')),
                ('root_domain', models.BigIntegerField(help_text='Hash-encoded root domain string.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(help_text='The scan whose RandomForest features are recorded here.', on_delete=django.db.models.deletion.CASCADE, related_name='pari_features', to='User.scan')),
            ],
            options={
                'db_table': 'pari_scan_features',
                'indexes': [models.Index(fields=['have_ip'], name='idx_sf_have_ip'), models.Index(fields=['secure_http'], name='idx_sf_secure_http'), models.Index(fields=['shortened'], name='idx_sf_shortened'), models.Index(fields=['have_ip', 'secure_http'], name='idx_sf_have_ip_secure_http')],
            },
        ),
    ]
