# Generated by Django 5.2.13 on 2026-09-30 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_pari_scan_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanFallbackResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='DeepAnalysis', help_text='Name of the fallback service (e.g. DeepAnalysis, Nikhil).', max_length=50)),
                ('classification', models.CharField(choices=[('Benign', 'Benign'), ('Phishing', 'Phishing'), ('Malware', 'Malware'), ('Defacement', 'Defacement'), ('Unknown', 'Unknown')], db_index=True, help_text='Final fallback classification result.', max_length=20)),
                ('risk_score', models.FloatField(help_text='Risk score 0.0–1.0 from the fallback pipeline.')),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, help_text='Categorical risk level returned by the fallback pipeline.', max_length=20, null=True)),
                ('evidence_summary', models.CharField(blank=True, default='', help_text='Bounded human-readable fallback evidence summary (max 500 chars).', max_length=500)),
                ('mongo_document_reference', models.CharField(blank=True, help_text='MongoDB document ID or reference string for the deep analysis case.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pari_scan_fallback',
            },
        ),
        migrations.AddField(
            model_name='prediction',
            name='is_confident',
            field=models.BooleanField(blank=True, db_index=True, help_text='True = scan was CONFIDENT (no fallback). False = UNCERTAIN (fallback triggered).', null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='threshold_used',
            field=models.FloatField(blank=True, help_text='Confidence threshold active at scan time (e.g. 0.75).', null=True),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['is_confident'], name='idx_pred_is_confident'),
        ),
        migrations.AddField(
            model_name='scanfallbackresult',
            name='scan',
            field=models.OneToOneField(help_text='The scan for which Nikhil fallback/deep analysis was performed.', on_delete=django.db.models.deletion.CASCADE, related_name='fallback_result', to='User.scan'),
        ),
        migrations.AddIndex(
            model_name='scanfallbackresult',
            index=models.Index(fields=['classification'], name='idx_sfb_classification'),
        ),
        migrations.AddIndex(
            model_name='scanfallbackresult',
            index=models.Index(fields=['risk_level'], name='idx_sfb_risk_level'),
        ),
        migrations.AddIndex(
            model_name='scanfallbackresult',
            index=models.Index(fields=['risk_score'], name='idx_sfb_risk_score'),
        ),
    ]
