# Generated by Django 5.2.13 on 2026-09-30 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_phase3_separate_initial_fallback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEvidenceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_family', models.CharField(choices=[('WEBPAGE', 'Webpage'), ('NETWORK', 'Network'), ('VISUAL', 'Visual'), ('THREAT_INTELLIGENCE', 'Threat Intelligence'), ('PROMPT_INJECTION', 'Prompt Injection'), ('SQL_HISTORY', 'SQL History'), ('TRUSTED_DOMAIN', 'Trusted Domain')], db_index=True, help_text='The evidence category / family (e.g. WEBPAGE, THREAT_INTELLIGENCE).', max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('UNAVAILABLE', 'Unavailable'), ('ERROR', 'Error'), ('SKIPPED', 'Skipped'), ('TIMEOUT', 'Timeout'), ('FAILED', 'Failed'), ('NO_MATCH', 'No Match'), ('PENDING', 'Pending'), ('NOT_RUN', 'Not Run')], default='PENDING', help_text='Execution status of this evidence family collector.', max_length=30)),
                ('detected', models.BooleanField(blank=True, db_index=True, help_text='True if indicators/threats were detected by this family. Null if not applicable.', null=True)),
                ('match_found', models.BooleanField(blank=True, db_index=True, help_text='True if intelligence match was found. Null if not applicable.', null=True)),
                ('source_count', models.IntegerField(blank=True, help_text='Number of external sources/feeds checked by this family. Null if not applicable.', null=True)),
                ('evidence_count', models.IntegerField(default=0, help_text='Count of discrete evidence items, indicators, or findings extracted.')),
                ('severity', models.CharField(blank=True, choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], help_text='Assessed severity level of the detected evidence if applicable.', max_length=20, null=True)),
                ('summary', models.CharField(blank=True, default='', help_text='Compact, bounded human-readable evidence summary (max 500 chars).', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(help_text='The scan this evidence summary belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_summaries', to='User.scan')),
            ],
            options={
                'db_table': 'pari_evidence_summary',
                'indexes': [models.Index(fields=['evidence_family'], name='idx_ev_family'), models.Index(fields=['evidence_family', 'match_found'], name='idx_ev_family_match'), models.Index(fields=['evidence_family', 'detected'], name='idx_ev_family_detected'), models.Index(fields=['status'], name='idx_ev_status')],
                'constraints': [models.UniqueConstraint(fields=('scan', 'evidence_family'), name='uq_scan_evidence_family')],
            },
        ),
    ]
