# Generated by Django 5.2.13 on 2026-09-30 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_scanevidencesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanAIEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, db_index=True, help_text='AI provider name (e.g. gemini, openrouter). Null if not run.', max_length=50, null=True)),
                ('model', models.CharField(blank=True, db_index=True, help_text='Model identifier used (e.g. gemini-2.5-flash). Null if not run.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('NOT_RUN', 'Not Run'), ('SUCCESS', 'Success'), ('COMPLETED', 'Completed'), ('UNAVAILABLE', 'Unavailable'), ('FAILED', 'Failed'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout'), ('RATE_LIMITED', 'Rate Limited'), ('QUOTA_EXCEEDED', 'Quota Exceeded')], db_index=True, default='NOT_RUN', help_text='Execution status of the AI module (NOT_RUN, SUCCESS, UNAVAILABLE, etc.).', max_length=30)),
                ('assessment', models.CharField(blank=True, choices=[('LIKELY_BENIGN', 'Likely Benign'), ('LIKELY_PHISHING', 'Likely Phishing'), ('LIKELY_MALWARE', 'Likely Malware'), ('LIKELY_DEFACEMENT', 'Likely Defacement'), ('CONFLICTING', 'Conflicting'), ('INCONCLUSIVE', 'Inconclusive'), ('Benign', 'Benign'), ('Phishing', 'Phishing'), ('Malware', 'Malware'), ('Defacement', 'Defacement'), ('Suspicious', 'Suspicious')], db_index=True, help_text='Structured AI assessment if returned (e.g. LIKELY_PHISHING). Null if not available.', max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, help_text='AI confidence score (0.0 to 1.0) only if returned by the AI provider. Null otherwise.', null=True)),
                ('risk_score', models.FloatField(blank=True, help_text='AI risk score (0.0 to 1.0) only if returned by the AI provider. Null otherwise.', null=True)),
                ('ai_required', models.BooleanField(db_index=True, default=False, help_text='True if the AI gatekeeper evaluated that AI analysis was required.')),
                ('ai_called', models.BooleanField(db_index=True, default=False, help_text='True if an external AI provider call was actually dispatched.')),
                ('reasoning_summary', models.CharField(blank=True, default='', help_text='Bounded, safe human-readable reasoning summary or gatekeeper decision reason.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(help_text='The scan whose AI evidence is summarized here.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_evidence', to='User.scan')),
            ],
            options={
                'db_table': 'pari_ai_evidence',
                'indexes': [models.Index(fields=['status'], name='idx_ai_status'), models.Index(fields=['provider'], name='idx_ai_provider'), models.Index(fields=['model'], name='idx_ai_model'), models.Index(fields=['assessment'], name='idx_ai_assessment'), models.Index(fields=['ai_required'], name='idx_ai_required'), models.Index(fields=['ai_called'], name='idx_ai_called')],
            },
        ),
    ]
