# Generated by Django 5.2.13 on 2026-09-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_scanaievidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanFinalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_classification', models.CharField(choices=[('Benign', 'Benign'), ('Phishing', 'Phishing'), ('Malware', 'Malware'), ('Defacement', 'Defacement'), ('Unknown', 'Unknown'), ('Needs Review', 'Needs Review')], db_index=True, help_text='Official final classification outcome.', max_length=20)),
                ('risk_score', models.FloatField(help_text='Official final risk score (0.0 to 1.0).')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, help_text='Categorical risk level (LOW, MEDIUM, HIGH, CRITICAL).', max_length=20)),
                ('decision_status', models.CharField(choices=[('FINAL', 'Final - Deterministic Corroboration'), ('CONFIDENT_ML', 'Confident - Initial Machine Learning'), ('NEEDS_REVIEW', 'Needs Review - Insufficient / Conflicting Evidence'), ('OVERRIDDEN', 'Overridden - Analyst Review')], db_index=True, default='FINAL', help_text='Decision status (FINAL, CONFIDENT_ML, NEEDS_REVIEW, etc.).', max_length=30)),
                ('decision_method', models.CharField(db_index=True, default='DETERMINISTIC_CORROBORATION', help_text='Method or subsystem that generated the final decision.', max_length=50)),
                ('corroboration_strength', models.CharField(blank=True, help_text='Strength of multi-family corroboration (e.g. STRONG, MODERATE, WEAK, NONE).', max_length=30, null=True)),
                ('evidence_family_count', models.IntegerField(default=0, help_text='Count of distinct independent evidence families contributing to the decision.')),
                ('conflict_detected', models.BooleanField(db_index=True, default=False, help_text='True if conflicting signals were observed between evidence families.')),
                ('decision_summary', models.CharField(blank=True, default='', help_text='Bounded human-readable decision summary.', max_length=500)),
                ('decision_timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the final decision was established.')),
            ],
            options={
                'db_table': 'pari_final_decision',
            },
        ),
        migrations.AddField(
            model_name='scanevidencesummary',
            name='source_component',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Primary subsystem or provider that gathered this evidence family (e.g. WebpageAnalyzer, ThreatIntelService).', max_length=100),
        ),
        migrations.AddField(
            model_name='scanindicator',
            name='reason',
            field=models.CharField(blank=True, default='', help_text='Structured explanation or trigger reason for recording this indicator', max_length=500),
        ),
        migrations.AddField(
            model_name='scanindicator',
            name='severity',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], help_text='Instance severity override if different from indicator definition', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scanindicator',
            name='source_component',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Subsystem/detector that produced this indicator (e.g. PARI, WebpageAnalyzer, NetworkAnalyzer, ThreatFox)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='scanevidencesummary',
            index=models.Index(fields=['source_component'], name='idx_ev_source_component'),
        ),
        migrations.AddIndex(
            model_name='scanindicator',
            index=models.Index(fields=['source_component'], name='idx_si_source'),
        ),
        migrations.AddField(
            model_name='scanfinaldecision',
            name='scan',
            field=models.OneToOneField(help_text='The scan whose official final decision is recorded here.', on_delete=django.db.models.deletion.CASCADE, related_name='final_decision', to='User.scan'),
        ),
        migrations.AddIndex(
            model_name='scanfinaldecision',
            index=models.Index(fields=['final_classification'], name='idx_fd_classification'),
        ),
        migrations.AddIndex(
            model_name='scanfinaldecision',
            index=models.Index(fields=['risk_level'], name='idx_fd_risk_level'),
        ),
        migrations.AddIndex(
            model_name='scanfinaldecision',
            index=models.Index(fields=['risk_score'], name='idx_fd_risk_score'),
        ),
        migrations.AddIndex(
            model_name='scanfinaldecision',
            index=models.Index(fields=['decision_method'], name='idx_fd_method'),
        ),
        migrations.AddIndex(
            model_name='scanfinaldecision',
            index=models.Index(fields=['decision_status'], name='idx_fd_status'),
        ),
        migrations.AddIndex(
            model_name='scanfinaldecision',
            index=models.Index(fields=['decision_timestamp'], name='idx_fd_timestamp'),
        ),
        migrations.AddIndex(
            model_name='scanfinaldecision',
            index=models.Index(fields=['final_classification', 'risk_level'], name='idx_fd_class_risk'),
        ),
    ]
